### ISSUE TITLE
Responsiveness Issue: Email View Clutter on Mobile Mode

### ISSUE THREAD

**Issue by VanshChitransh** [muzammildafedar/udayah#12]
### Description:
There is a responsiveness issue on the udayah website when switching from laptop mode to mobile mode. The layout looks fine on laptop screens, but it doesn't work as expected on mobile screens. Below are the screenshots to demonstrate the issue:

### 💻 Laptop Mode Screenshot:
![Screenshot from 2024-09-27 14-21-19](https://github.com/user-attachments/assets/ca7fe643-f122-45b1-bc1c-69e433bd2aab)

### 📱 Mobile Mode Screenshot:
![Screenshot from 2024-09-27 14-21-44](https://github.com/user-attachments/assets/4577f3ac-1d44-4cd7-b2e4-0ea1826643c7)

### Actual Error:
- In mobile view, when a user clicks on a particular email, the email format opens on the same page, causing the layout to become cluttered. 
- Expected Behavior: On mobile view, when an email is clicked, it should navigate to a new page to display the email format, with a back button to return to the list of emails.
  
### Steps to Reproduce:
1. Open the website on a mobile device or resize the browser to mobile dimensions.
2. Click on an email from the list.
3. Observe that the email format opens on the same page, without the option to return to the previous page easily.

### Expected Behavior:
- When a user clicks on an email in mobile view, the selected email should open in a new page.
- A back button should be available to return to the list of emails.

### Environment:
- Device: Mobile (e.g., iPhone 12, Pixel 5)
- Browser: Chrome, Safari, Firefox, etc.
- OS: Android, iOS

### Additional Notes:
This improvement is required to enhance the mobile user experience and ensure better navigation between pages.

**Comment by VanshChitransh** [comment]
@muzammildafedar i would like to take this issue.

**Comment by muzammildafedar** [comment]
Thanks for raising an issue, @VanshChitransh  Feel free to go ahead and take on the issue. Let me know if you need any help or clarification. Looking forward to your contributions!

**Comment by Rakan-Makhashin** [comment]
I got this behavior when fixing it
when email is not selected
![unselected](https://github.com/user-attachments/assets/d3358653-e3b7-4fc4-b34a-baf025506a10)

when email is selected
![selected](https://github.com/user-attachments/assets/56ca050c-6c2e-4797-9828-18d6ba89c0d3)

the back button when pressed take you back to the unselected page/view

is this what is needed ? @muzammildafedar

**Comment by muzammildafedar** [comment]
> I got this behavior when fixing it when email is not selected ![unselected](https://private-user-images.githubusercontent.com/112309932/371634424-d3358653-e3b7-4fc4-b34a-baf025506a10.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjIxMjcsIm5iZiI6MTcyNzQ2MTgyNywicGF0aCI6Ii8xMTIzMDk5MzIvMzcxNjM0NDI0LWQzMzU4NjUzLWUzYjctNGZjNC1iMzRhLWJhZjAyNTUwNmExMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxODMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzQ2NDU3MWJlN2EyMTNjNjUwYjcwYWJlYzUzM2RkMzllYTNjNjAzNWI1OTFjZjE1M2ZkYjc0MGJjYTE5ZjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._eZAA1PMy5rfCqUFL1rxGtDLK2GxqbwNiY8ZXGWkRxQ)
> 
> when email is selected ![selected](https://private-user-images.githubusercontent.com/112309932/371634501-56ca050c-6c2e-4797-9828-18d6ba89c0d3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjIxMjcsIm5iZiI6MTcyNzQ2MTgyNywicGF0aCI6Ii8xMTIzMDk5MzIvMzcxNjM0NTAxLTU2Y2EwNTBjLTZjMmUtNDc5Ny05ODI4LTE4ZDZiYTg5YzBkMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxODMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWY1ODA2OTE2YjE4NzBkM2U0M2ZiOTAyMDkyN2UzMTZlYjM0OGRhN2E5ZDBjM2RlN2Q0MDFmZjBlMmM4NGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l3Ew0Oa6Skf_dxQDqE__E2a3ziCpmnSZTIHmGqoS65s)
> 
> the back button when pressed take you back to the unselected page/view
> 
> is this what is needed ? @muzammildafedar

Yes this expected but in the email list we don't need to display "please choose email" in half screen and it will taking half of screen. it will be good we will display only email list. On click each email it should need to comes to second image as you attached.

**Comment by Rakan-Makhashin** [comment]
I think i did commit this fix with the #4 issue in the same pull request check it out

**Comment by muzammildafedar** [comment]
The reported issue has been successfully fixed. PR #10
