### ISSUE TITLE
Feature Request: Display username, email address, and profile photo from firebase authentication

### ISSUE THREAD

**Issue by muzammildafedar** [muzammildafedar/udayah#15]
**Description:**
We need to implement a feature in the Flutter app that displays the authenticated user's profile information, including:

- Username (display name)
- Email address
- Profile photo (if available)

This data should be fetched from Firebase Authentication once the user has successfully logged in and then displayed in the UI.

**Acceptance Criteria:**

- Retrieve user data (display name, email, and profile photo URL) from Firebase Authentication after login.
- Display the username and email address in the designated fields within the profile section of the app.
- Show the user's profile photo (if available) in an avatar or circular image widget.
- If the user does not have a profile photo, display a default avatar placeholder.
-

**Tasks:**

1.  Fetch user details from FirebaseAuth.
2.  Implement the UI to show the username, email, and profile photo.
3.  Handle cases where the profile photo is not available.

**References:**

- [Firebase Auth Documentation](https://firebase.flutter.dev/docs/auth/usage/)
- [Flutter FirebaseAuth Plugin](https://pub.dev/packages/firebase_auth)

**Comment by sowunmi-mayowa** [comment]
I can handle this if it was just for the web (react). Now that it is flutter i don't want to start what i cant finish

**Comment by muzammildafedar** [comment]
> I can handle this if it was just for the web (react). Now that it is flutter i don't want to start what i cant finish

Thank you for your interest in contributing to Udayah. If you’re not familiar with Flutter, you’re welcome to contribute to the Node.js side. I believe your contributions will be incredibly valuable to Udayah.

**Comment by sanarawal7** [comment]
I would like to work on this!

**Comment by xkaper001** [comment]
Hi @muzammildafedar,

I noticed that this issue is unassigned, and I'd love to work on it! I'm familiar with the technology used in this project and I believe I can help resolve it.

Could you please assign this issue to me?

Thank you!

**Comment by Atharva-Werulkar** [comment]
Hello,

I'd love to work on this issue! I have significant experience with Firebase, having integrated Firebase Authentication and Firestore in multiple projects. Implementing user profile features, such as fetching and displaying user data (display name, email, profile photo), is something I've worked on before.

I will retrieve the user's information from Firebase Authentication upon login and display the data in the app's profile section. I'll also ensure that a default avatar is shown when the user does not have a profile photo.

Looking forward to contributing!

Best regards,
Atharva Werulkar

**Comment by muzammildafedar** [comment]
Thanks for your interest, @Atharva-Werulkar and @xkaper001 . This issue has been assigned to @xkaper001. @Atharva-Werulkar there is an alignment issue when the we select the emails. You can observe the "status" and the "added by" section. For this, you will need to create a new issue. If you would like to add any new features or any enhancement , we always welcome your contributions. Looking forward to your contributions, guys!

**Comment by Atharva-Werulkar** [comment]
Sure!!,
I'll look into that and create an issue for it

**Comment by xkaper001** [comment]
@muzammildafedar, I just had a query regarding this issue.

For integrating user details from their google account into the flutter app do I have to create my own project in the firebase console, connect it with the app and then integrate it? :')

**Comment by muzammildafedar** [comment]
> @muzammildafedar, I just had a query regarding this issue.
> 
> For integrating user details from their google account into the flutter app do I have to create my own project in my firebase console, connect it with the app and then work on it? :')

Yes, you have to connect your own firebase to the app. 

ref: https://firebase.google.com/docs/flutter/setup?platform=web

**Comment by muzammildafedar** [comment]
@Atharva-Werulkar would you like to take the issue #22

**Comment by Atharva-Werulkar** [comment]
Yes, 
You can assign the issue to me

**Comment by muzammildafedar** [comment]
> Yes, You can assign the issue to me

Not able to assign you. Could you please comment on #22 issue ?

**Comment by xkaper001** [comment]
@muzammildafedar can you please add `hacktoberfest` tag to this issue.

**Comment by xkaper001** [comment]
also @muzammildafedar,
> Display the username and email address in the designated fields within the profile section of the app.

I don't see a **profile section** in the app. where should I make the profile section? Should I add another tab in the `NavigationPanel` by adding one more item to `NavigationItems` or a constant section on the topright of the page? (like google uses).

**Comment by muzammildafedar** [comment]
You have implement Profile section inside the NavigationPane.

> also @muzammildafedar,
> 
> > Display the username and email address in the designated fields within the profile section of the app.
> 
> I don't see a **profile section** in the app. where should I make the profile section? Should I add another tab in the `NavigationPanel` by adding one more item to `NavigationItems` or a constant section on the topright of the page? (like google uses).
