### ISSUE TITLE
Misalignment in Bottom Navigation Bar - Mobile View

### ISSUE THREAD

**Issue by muzammildafedar** [muzammildafedar/udayah#18]
**Description:** 

The icons in the bottom navigation bar are misaligned. The home icon appears lower than the settings and logout icons, leading to an uneven visual layout, as seen in the attached screenshot.

**Expected Behavior:** 

All icons in the bottom navigation bar should be vertically centered and aligned with each other.

**Steps to Reproduce:**

1. Navigate to any screen with the bottom navigation bar.
2. Observe the misalignment of icons (especially the home icon being lower than others).

**Possible Fix:**

Review the BottomNavigationBar widget or container where the icons are placed.
Adjust the padding, alignment, or centered properties to ensure all icons align properly.

<img width="515" alt="Screenshot 2024-10-01 at 10 06 15 PM" src="https://github.com/user-attachments/assets/bcd6c4c3-2c30-4e45-9a17-7a1a711d505a">

**Comment by RishavKumarSinha** [comment]
Hi, I am interested in this issue. Can I work on it?

**Comment by muzammildafedar** [comment]
@RishavKumarSinha assigned! Thanks for your interest!

**Comment by muzammildafedar** [comment]
Resolved. Thanks !
