### ISSUE TITLE
Feature Request: Add User Alert for "Copy" Button Action

### ISSUE THREAD

**Issue by muzammildafedar** [muzammildafedar/udayah#24]
**Description:**

When a user clicks the "Copy" button to copy the email address, the action works correctly; however, there is no alert or feedback provided to the user confirming that the email address has been successfully copied. To improve user experience, I suggest implementing a notification alert using our custom widget.

**Steps to Reproduce:**

1. Navigate to the section with the "Copy" button.
2. Click the "Copy" button.

**Expected Behavior:**

- After clicking the "Copy" button, the user should receive an alert notification indicating that the email address has been successfully copied to the clipboard.

**Actual Behavior:**

- Currently, there is no feedback provided to the user after clicking the "Copy" button, which may lead to confusion about whether the action was successful.

**Proposed Solution:**

- Utilize the custom widget we have in our codebase to display an alert notification to the user after the "Copy" action is performed.

**Screenshots:**

<img width="347" alt="Screenshot 2024-10-03 at 10 08 33 PM" src="https://github.com/user-attachments/assets/65a93fe6-8310-43f3-9bb5-76e46410a562">

**Comment by IngaleChinmay04** [comment]
I'm interested in fixing the missing feedback after the 'Copy' action. I can use the TossBar widget for the solution. Could you please assign this issue to me?

**Comment by muzammildafedar** [comment]
@IngaleChinmay04 assigned ! Thanks for your interest.

**Comment by may-tas** [comment]
I want to work on this issue if its still open @muzammildafedar .

**Comment by muzammildafedar** [comment]
@IngaleChinmay04 how's your progress on this? FYI, I'll need to un-assign you soon if I don't hear back.

**Comment by IngaleChinmay04** [comment]
hi, I am sorry I am unable to do it as I tried to setup but setuping the project is getting problems.

I am getting the following

lib/main.dart:4:8: Error: Error when reading 'lib/firebase_options.dart': The system cannot find the file specified.  

import 'package:udayah/firebase_options.dart';
       ^
lib/main.dart:18:41: Error: Undefined name 'DefaultFirebaseOptions'.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
                                        ^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/src/widgets/toolbar_widget.dart:1123:68:  
Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                style: Theme.of(context).textTheme.headline6),
                                                                   ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/src/widgets/toolbar_widget.dart:1875:56:  
Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                                      .bodyText1
                                                       ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/src/widgets/toolbar_widget.dart:1982:56:  
Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                                      .bodyText1
                                                       ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/src/widgets/toolbar_widget.dart:2134:56:  
Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                                      .bodyText1
                                                       ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/src/widgets/toolbar_widget.dart:2286:56:  
Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                                      .bodyText1
                                                       ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/src/widgets/toolbar_widget.dart:2438:56:
Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                                      .bodyText1
                                                       ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/utils/utils.dart:952:51: Error: The getter
'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
      widget.style ?? Theme.of(context).textTheme.subtitle1;
                                                  ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/html_editor_enhanced-2.5.1/lib/utils/utils.dart:1012:37: Error: The      
getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/installation%20flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
        Theme.of(context).textTheme.subtitle1!.fontSize!;
                                    ^^^^^^^^^
Waiting for connection from debug service on Chrome...             75.9s
Failed to compile application.

C:\Users\dell inspiron\Desktop\udayah\lib>

**Comment by may-tas** [comment]
Hey @muzammildafedar can I take this issue on?

**Comment by muzammildafedar** [comment]
@IngaleChinmay04 Could you please fire your own firebase setup to local repo ?
Ref: https://firebase.google.com/docs/flutter/setup?platform=web

@may-tas Thanks for your interest, You can pick any other open issues which are unassigned. And you can open new issue for new feature anything if you want to add/Improvement to the current design.

**Comment by may-tas** [comment]
yeah sure.

**Comment by IngaleChinmay04** [comment]
I am getting the above problem after I setup with firebase. I had created my firebase project and connected to flutter

**Comment by xkaper001** [comment]
Hey @muzammildafedar, It's been more than a week since this issue was last worked on. Could you assign me this issue?

**Comment by maiHydrogen** [comment]
hey @muzammildafedar as i can see the previous assignee has removed himself from the issue can i work on this?? i'm really excited to do it

**Comment by muzammildafedar** [comment]
> hey @muzammildafedar as i can see the previous assignee has removed himself from the issue can i work on this?? i'm really excited to do it

Thanks for your interest. This issue has assigned to @xkaper001 and @maiHydrogen You can pick any other open issue.
