### ISSUE TITLE
Alignment Issue with "Test" and "Send Cold Email" Buttons - Mobile View

### ISSUE THREAD

**Issue by muzammildafedar** [muzammildafedar/udayah#25]
**Description:**

There is an alignment issue with the "Test" and "Send Cold Email" buttons in the email content section of the dashboard. The buttons are not aligned properly, affecting the visual consistency of the user interface.

**Steps to Reproduce:**

1. Navigate to the dashboard.
2. Observe the positioning of the "Test" and "Send Cold Email" buttons below the email content area.

**Expected Behavior:**

- The "Test" and "Send Cold Email" buttons should be aligned consistently, ensuring equal spacing and visual balance.

**Actual Behavior:**

- The buttons are misaligned, which detracts from the overall aesthetics and usability of the dashboard.

**Screenshots:**

<img width="420" alt="Screenshot 2024-10-03 at 10 27 39 PM" src="https://github.com/user-attachments/assets/b73b777d-5e81-46b9-9588-e74874515eec">

**Comment by mumtazmumtazfb** [comment]
I would like to complete this task. Can you please assign it to me?

**Comment by muzammildafedar** [comment]
@mumtazmumtazfb assigned ! Thanks for your interest.

**Comment by xkaper001** [comment]
Hey @muzammildafedar it has been more than a week, and there has been no update on this issue. Please assign me this issue. I'll would like to work on this one.

**Comment by tanayduddalwar** [comment]
@xkaper001 please assign me this issue

**Comment by xkaper001** [comment]
@tanayduddalwar Hi mate, I am a contributor just like you, and also I'm working on this issue, will prolly raise a PR by tomorrow :)
