### ISSUE TITLE
firebase_options.dart file not present in the codebase

### ISSUE THREAD

**Issue by may-tas** [muzammildafedar/udayah#28]
Description : Currently the main.dart file is showing error as it cannot access DefaultFirebaseOptions.currentPlatform.
Fix : Add firebase_options.dart file to ensure app works as before.
firebase_options.dart file can be generated once as the project is connected to a firebase project on console.

**Comment by may-tas** [comment]
@muzammildafedar whoever has created the firebase console project for this repo, they can add the file to it.

**Comment by muzammildafedar** [comment]
@may-tas You can set up your own Firebase for now. We are currently working on a development mode Firebase setup for everyone, but it is still a work in progress.


Reference: [Set up Firebase for your own project](https://firebase.google.com/docs/flutter/setup?platform=web)

**Comment by may-tas** [comment]
okay got it !
