### ISSUE TITLE
initial backend setup

### ISSUE THREAD

**Issue by Rakan-Makhashin** [muzammildafedar/udayah#8]
**Description:**

To establish a robust backend for our application, we need to set up an initial structure that includes the MVC (Model-View-Controller) pattern, Express.js framework, ORM. This setup will lay the foundation for further development and feature additions.

### **Feature Requirements:**

**MVC Structure:**
Organize the project files into a clear MVC structure to separate concerns effectively.

**Express Setup:**
Set up an Express server to handle incoming requests and route them appropriately.

**Database Configuration:**
Configure ORM to connect to a PostgreSQL database.
Ensure proper error handling for database connections.

**Model Definitions:**
Create initial models based on the database schema requirements.
Ensure the models are properly defined to interact with the database.

**Controller Implementation:**
Develop controllers to manage the business logic for various endpoints.

**Environment Configuration:**
Use environment variables to manage sensitive information.

**Comment by muzammildafedar** [comment]
The reported issue has been successfully fixed. PR #10
